### ISSUE TITLE
Zenodo: BLR subgroups

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#212] opened 2015-03-17 15:03 UTC
We have a new corpus of articles in preparation (ca 16,000) that cover fruitflies. A request from the builder of this corpus is, that he would like to provide access that includes only this body, Eg search for an author name and get only publications that relate to this body.

How can we make this happen?

Do we have to include to each articles a key world "fruitfly" or "Drosophilidae", or is there another way around?
Can we provide on the introductionary page a button to (sub) collections and  which then would lead to a new window that provides access only to those fruitfly publications?

This collection is very important for science, since it covers one of the biological model organism. At the same time, it is good for BLR to include it, not least to keep management of this group simple.

Any hint welcome

Donat

**Comment by lnielsen** [comment] 2017-01-18 07:45
Duplicate of #68

**Closed by lnielsen** 2017-01-18 07:45 UTC
