### ISSUE TITLE
Link from GitHub repos list to deposit on Zenodo does work

### ISSUE THREAD

**Issue by xrotwang** [zenodo/zenodo#355] opened 2015-07-09 08:28 UTC
From the [list of GitHub repos](https://zenodo.org/account/settings/github/) the links to deposits of the latest release on Zenodo do not work. The `href` attribute of the links is empty, possibly because `doi_url` [here](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/github/templates/github/index_base.html#L119) is undefined? Maybe it should be `latest_dep.doi_url`?

**Comment by bouzlibop** [comment] 2015-07-09 08:36
@xrotwang, this issue should be resolved soon by this PR: https://github.com/zenodo/zenodo/pull/336

**Comment by bouzlibop** [comment] 2015-07-09 08:39
If you don't mind I will close this issue and in case you have some further comments on it please do not hesitate to put them in the issue mentioned below.

**Comment by bouzlibop** [comment] 2015-07-09 08:39
Is a duplicate of https://github.com/zenodo/zenodo/issues/276

**Closed by bouzlibop** 2015-07-09 08:39 UTC
Labels: bug, duplicate

**Comment by xrotwang** [comment] 2015-07-09 08:52
Closing this is fine. Btw how often is the software deployed to zenodo.org?

**Comment by bouzlibop** [comment] 2015-07-09 09:11
Usually it's every 2 weeks. Although it might get extended during July and August, because of vacation time.
