### ISSUE TITLE
records: export pages should include record title 

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#81] opened 2014-12-09 11:22 UTC
Related to #80 

![sedfitter a python sed fitting tool google search](https://cloud.githubusercontent.com/assets/1698163/5356534/eb1a81de-7f9d-11e4-8272-d758397f111d.png)

**Comment by bouzlibop** [comment] 2015-01-20 08:27
@lnielsen, after some investigation, here are the results: 

Basing on [this answer](http://webmasters.stackexchange.com/questions/44372/my-website-title-shows-up-slightly-different-from-whats-in-my-title-tag-only-i/44374#44374) and the references included in it I tempted to say that the solution here would be just to change the `h1` of the specific export pages (as so it also includes the desirable record title). The problem is that I'm not sure how would I be able to test this assumption?

Note:
For both sites (MARC export and main record page) the result which I get in google webmasters tools is the same, see: 
* result for [https://zenodo.org/record/13149](http://www.google.com/webmasters/tools/richsnippets?q=https%3A%2F%2Fzenodo.org%2Frecord%2F13149)
* result for [https://zenodo.org/record/13149/export/hm](http://www.google.com/webmasters/tools/richsnippets?q=https%3A%2F%2Fzenodo.org%2Frecord%2F13149%2Fexport%2Fhm)

**Comment by bouzlibop** [comment] 2015-01-22 16:45
Above mentioned PR should close this issue. 

_NOTE_: More to follow in https://github.com/zenodo/zenodo/issues/80

**Closed** 2015-02-02 09:14 UTC
Labels: 3 - Done, bug
