### ISSUE TITLE
wrong relationType in metadata records describing software

### ISSUE THREAD

**Issue by joschirr** [zenodo/zenodo#1294] opened 2017-09-22 11:37 UTC
actually two issues:

1. according to the DOI versioning concept of zenodo I would expect the relationType "isVersionOf" instead of "isPartOf" in the metadata describing software.
2. does zenodo also expose the DOI "concept" metadata records ?

(related issue number in OpenAIRE redmine: 3124)

**Comment by krzysztof** [comment] 2017-09-25 15:24
Dear @joschirr

1. the "HasVersions" "isVersionOf" is currently not supported in DataCite 4.0, but is only in planning for the next version: https://schema.test.datacite.org/
We plan to upgrade our relation types to those terms as soon as we can upgrade to the new datacite schema.
2. The concept DOI is currently implemented, so that it always resolves to the latest version of the record - it does not contain a separate metadata yet. On the datacite export side side, we do submit the copy of the latest version's record under the concept DOI, and update it accordingly as new versions are released.

**Comment by joschirr** [comment] 2017-09-25 15:35
thanks. I should have taken a closer look at
https://schema.datacite.org/meta/kernel-4.0/include/datacite-relationType-v4.xsd
But I wonder if "IsNewVersionOf" / "IsPreviousVersionOf" could somehow better describe the relation between different versions of a software than "isPartOf" which sounds like a software is splitted into several files.

**Comment by krzysztof** [comment] 2017-10-05 09:58
@joschirr The isPartOf is only a relation from the record DOI to a "Concept DOI" (and vice-versa). Concept DOI is kind of a higher-level DOI which describes multiple versions of the same resource. DOIs which are "across" the version sequence do not relate to one another yet. The isNewVersionOf/isPreviousVersionOf was in planning and was actually implemented, but we decided not to use it in the end because of lack of proper semantic versioning support for something like software, e.g.: minor release "1.5.1" would be a "nextVersionOf" of a version "1.6.0".

**Comment by lnielsen** [comment] 2017-10-31 08:26
@joschirr DataCite v4.1 is out now, so we'll update to use the new relationship. 

The main difference between ``is(New|Previous)VersionOf`` vs ``(is|has)(Version|Part)(Of|s)`` is that the latter is *unordered* and the former is *ordered*. Only very simply versioning follows a linear ordering - e.g. most software versioning is actually a tree structure if they are using semantic versioning.

**Comment by lnielsen** [comment] 2017-10-31 08:28
Closing as duplicate of #1146

**Closed by lnielsen** 2017-10-31 08:28 UTC
