### ISSUE TITLE
A GitHub release failed to upload to Zenodo

### ISSUE THREAD

**Issue by karel-brinda** [zenodo/zenodo#1359] opened 2017-11-26 18:41 UTC
## Error

```
{
    "errors": "Unknown error occured."
}
```

## GitHub Payload

```{
    "action": "published", 
    "release": {
        "body": "## Improvements\r\n\r\n* If the HTSlib submodule is missing, download it from Github", 
        "tag_name": "0.1.2.5", 
        "assets_url": "https://api.github.com/repos/karel-brinda/ococo/releases/8659241/assets", 
        "assets": [], 
        "upload_url": "https://uploads.github.com/repos/karel-brinda/ococo/releases/8659241/assets{?name,label}", 
        "author": {
            "following_url": "https://api.github.com/users/karel-brinda/following{/other_user}", 
            "gists_url": "https://api.github.com/users/karel-brinda/gists{/gist_id}", 
            "organizations_url": "https://api.github.com/users/karel-brinda/orgs", 
            "url": "https://api.github.com/users/karel-brinda", 
            "events_url": "https://api.github.com/users/karel-brinda/events{/privacy}", 
            "html_url": "https://github.com/karel-brinda", 
            "subscriptions_url": "https://api.github.com/users/karel-brinda/subscriptions", 
            "avatar_url": "https://avatars3.githubusercontent.com/u/8779046?v=4", 
            "repos_url": "https://api.github.com/users/karel-brinda/repos", 
            "received_events_url": "https://api.github.com/users/karel-brinda/received_events", 
            "gravatar_id": "", 
            "starred_url": "https://api.github.com/users/karel-brinda/starred{/owner}{/repo}", 
            "site_admin": false, 
            "login": "karel-brinda", 
            "type": "User", 
            "id": 8779046, 
            "followers_url": "https://api.github.com/users/karel-brinda/followers"
        }, 
        "url": "https://api.github.com/repos/karel-brinda/ococo/releases/8659241", 
        "created_at": "2017-11-26T18:23:26Z", 
        "target_commitish": "master", 
        "html_url": "https://github.com/karel-brinda/ococo/releases/tag/0.1.2.5", 
        "zipball_url": "https://api.github.com/repos/karel-brinda/ococo/zipball/0.1.2.5", 
        "published_at": "2017-11-26T18:26:04Z", 
        "draft": false, 
        "prerelease": false, 
        "tarball_url": "https://api.github.com/repos/karel-brinda/ococo/tarball/0.1.2.5", 
        "id": 8659241, 
        "name": "Ococo 0.1.2.5"
    }, 
    "sender": {
        "following_url": "https://api.github.com/users/karel-brinda/following{/other_user}", 
        "gists_url": "https://api.github.com/users/karel-brinda/gists{/gist_id}", 
        "organizations_url": "https://api.github.com/users/karel-brinda/orgs", 
        "url": "https://api.github.com/users/karel-brinda", 
        "events_url": "https://api.github.com/users/karel-brinda/events{/privacy}", 
        "html_url": "https://github.com/karel-brinda", 
        "subscriptions_url": "https://api.github.com/users/karel-brinda/subscriptions", 
        "avatar_url": "https://avatars3.githubusercontent.com/u/8779046?v=4", 
        "repos_url": "https://api.github.com/users/karel-brinda/repos", 
        "received_events_url": "https://api.github.com/users/karel-brinda/received_events", 
        "gravatar_id": "", 
        "starred_url": "https://api.github.com/users/karel-brinda/starred{/owner}{/repo}", 
        "site_admin": false, 
        "login": "karel-brinda", 
        "type": "User", 
        "id": 8779046, 
        "followers_url": "https://api.github.com/users/karel-brinda/followers"
    }, 
    "repository": {
        "issues_url": "https://api.github.com/repos/karel-brinda/ococo/issues{/number}", 
        "deployments_url": "https://api.github.com/repos/karel-brinda/ococo/deployments", 
        "svn_url": "https://github.com/karel-brinda/ococo", 
        "has_wiki": true, 
        "forks_url": "https://api.github.com/repos/karel-brinda/ococo/forks", 
        "mirror_url": null, 
        "stargazers_count": 27, 
        "subscription_url": "https://api.github.com/repos/karel-brinda/ococo/subscription", 
        "notifications_url": "https://api.github.com/repos/karel-brinda/ococo/notifications{?since,all,participating}", 
        "collaborators_url": "https://api.github.com/repos/karel-brinda/ococo/collaborators{/collaborator}", 
        "updated_at": "2017-09-28T12:28:57Z", 
        "private": false, 
        "pulls_url": "https://api.github.com/repos/karel-brinda/ococo/pulls{/number}", 
        "owner": {
            "following_url": "https://api.github.com/users/karel-brinda/following{/other_user}", 
            "gists_url": "https://api.github.com/users/karel-brinda/gists{/gist_id}", 
            "organizations_url": "https://api.github.com/users/karel-brinda/orgs", 
            "url": "https://api.github.com/users/karel-brinda", 
            "events_url": "https://api.github.com/users/karel-brinda/events{/privacy}", 
            "html_url": "https://github.com/karel-brinda", 
            "subscriptions_url": "https://api.github.com/users/karel-brinda/subscriptions", 
            "avatar_url": "https://avatars3.githubusercontent.com/u/8779046?v=4", 
            "repos_url": "https://api.github.com/users/karel-brinda/repos", 
            "received_events_url": "https://api.github.com/users/karel-brinda/received_events", 
            "gravatar_id": "", 
            "starred_url": "https://api.github.com/users/karel-brinda/starred{/owner}{/repo}", 
            "site_admin": false, 
            "login": "karel-brinda", 
            "type": "User", 
            "id": 8779046, 
            "followers_url": "https://api.github.com/users/karel-brinda/followers"
        }, 
        "full_name": "karel-brinda/ococo", 
        "issue_comment_url": "https://api.github.com/repos/karel-brinda/ococo/issues/comments{/number}", 
        "contributors_url": "https://api.github.com/repos/karel-brinda/ococo/contributors", 
        "id": 45266025, 
        "keys_url": "https://api.github.com/repos/karel-brinda/ococo/keys{/key_id}", 
        "issue_events_url": "https://api.github.com/repos/karel-brinda/ococo/issues/events{/number}", 
        "tags_url": "https://api.github.com/repos/karel-brinda/ococo/tags", 
        "archived": false, 
        "downloads_url": "https://api.github.com/repos/karel-brinda/ococo/downloads", 
        "assignees_url": "https://api.github.com/repos/karel-brinda/ococo/assignees{/user}", 
        "contents_url": "https://api.github.com/repos/karel-brinda/ococo/contents/{+path}", 
        "has_pages": false, 
        "git_refs_url": "https://api.github.com/repos/karel-brinda/ococo/git/refs{/sha}", 
        "open_issues_count": 6, 
        "has_projects": true, 
        "clone_url": "https://github.com/karel-brinda/ococo.git", 
        "watchers_count": 27, 
        "git_tags_url": "https://api.github.com/repos/karel-brinda/ococo/git/tags{/sha}", 
        "labels_url": "https://api.github.com/repos/karel-brinda/ococo/labels{/name}", 
        "forks": 2, 
        "size": 2669, 
        "homepage": "http://arxiv.org/abs/1605.09070", 
        "fork": false, 
        "milestones_url": "https://api.github.com/repos/karel-brinda/ococo/milestones{/number}", 
        "commits_url": "https://api.github.com/repos/karel-brinda/ococo/commits{/sha}", 
        "releases_url": "https://api.github.com/repos/karel-brinda/ococo/releases{/id}", 
        "description": "OCOCO: the first online consensus caller. Call genomic consensus directly from an unsorted SAM/BAM stream.", 
        "archive_url": "https://api.github.com/repos/karel-brinda/ococo/{archive_format}{/ref}", 
        "comments_url": "https://api.github.com/repos/karel-brinda/ococo/comments{/number}", 
        "events_url": "https://api.github.com/repos/karel-brinda/ococo/events", 
        "default_branch": "master", 
        "html_url": "https://github.com/karel-brinda/ococo", 
        "compare_url": "https://api.github.com/repos/karel-brinda/ococo/compare/{base}...{head}", 
        "trees_url": "https://api.github.com/repos/karel-brinda/ococo/git/trees{/sha}", 
        "watchers": 27, 
        "git_url": "git://github.com/karel-brinda/ococo.git", 
        "forks_count": 2, 
        "merges_url": "https://api.github.com/repos/karel-brinda/ococo/merges", 
        "has_issues": true, 
        "ssh_url": "git@github.com:karel-brinda/ococo.git", 
        "blobs_url": "https://api.github.com/repos/karel-brinda/ococo/git/blobs{/sha}", 
        "git_commits_url": "https://api.github.com/repos/karel-brinda/ococo/git/commits{/sha}", 
        "hooks_url": "https://api.github.com/repos/karel-brinda/ococo/hooks", 
        "has_downloads": true, 
        "languages_url": "https://api.github.com/repos/karel-brinda/ococo/languages", 
        "name": "ococo", 
        "language": "C++", 
        "url": "https://api.github.com/repos/karel-brinda/ococo", 
        "subscribers_url": "https://api.github.com/repos/karel-brinda/ococo/subscribers", 
        "created_at": "2015-10-30T17:26:34Z", 
        "pushed_at": "2017-11-26T18:26:04Z", 
        "teams_url": "https://api.github.com/repos/karel-brinda/ococo/teams", 
        "open_issues": 6, 
        "branches_url": "https://api.github.com/repos/karel-brinda/ococo/branches{/branch}", 
        "statuses_url": "https://api.github.com/repos/karel-brinda/ococo/statuses/{sha}", 
        "stargazers_url": "https://api.github.com/repos/karel-brinda/ococo/stargazers"
    }
}
```

**Comment by karel-brinda** [comment] 2017-11-26 18:47
After removing the release and creating a new identical one, everything worked.

**Comment by ManavalanG** [comment] 2017-11-27 21:46
I got the same "unknown" error (haven't looked at payload logs yet. Not sure what to look at). Is use three element semantic versioning necessary? I use something like Oct2017, Nov2017, etc. Would that be cause of the error in my case?

Correponding release with this error- https://github.com/HudsonAlpha/uniprot_genomic/releases/tag/Nov2017

**Comment by samapriya** [comment] 2017-11-29 03:08
Same issue tried twice and problem remains, getting 
```
{
    "errors": "Unknown error occured."
}
```

Even though action says published (Tried this twice but nothing happened)

The Payload was
```
{
    "action": "published", 
    "release": {
        "body": "Google Earth Engine Batch Asset Manager with Addons are additional tools were added to include functionality for moving assets, conversion of objects to fusion table, cleaning folders, querying tasks apart from uploading and deleting assets from collections. The ambition is apart from helping user with batch actions on assets along with interacting and extending capabilities of existing GEE CLI(Google Earth Engine Command Line Interface).tab. The new release also contains options to change collection properties, query and generate reports of all task running, and to copy collection from one user to another or from one collection to another. It is developed case by case basis to include more features in the future as it becomes available or as need arises.\r\n\r\n### Changelog\r\n#### v0.2.2\r\n- Added improvement to earthengine authorization\r\n\r\n#### v0.2.1\r\n- Added capability to handle PlanetScope 4Band Surface Reflectance Metadata Type\r\n- General Improvements\r\n\r\n#### v0.2.0\r\n- Tool improvements and enhancements\r\n\r\n#### v0.1.9\r\n- New tool EE_Report was added\r\n\r\n#### v0.1.8\r\n- Fixed issues with install\r\n- Dependcies now part of setup.py\r\n- Updated Parser and general improvements\r\n", 
        "tag_name": "0.2.2", 
        "assets_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/releases/8694239/assets", 
        "assets": [], 
        "upload_url": "https://uploads.github.com/repos/samapriya/gee_asset_manager_addon/releases/8694239/assets{?name,label}", 
        "author": {
            "following_url": "https://api.github.com/users/samapriya/following{/other_user}", 
            "gists_url": "https://api.github.com/users/samapriya/gists{/gist_id}", 
            "organizations_url": "https://api.github.com/users/samapriya/orgs", 
            "url": "https://api.github.com/users/samapriya", 
            "events_url": "https://api.github.com/users/samapriya/events{/privacy}", 
            "html_url": "https://github.com/samapriya", 
            "subscriptions_url": "https://api.github.com/users/samapriya/subscriptions", 
            "avatar_url": "https://avatars3.githubusercontent.com/u/6677629?v=4", 
            "repos_url": "https://api.github.com/users/samapriya/repos", 
            "received_events_url": "https://api.github.com/users/samapriya/received_events", 
            "gravatar_id": "", 
            "starred_url": "https://api.github.com/users/samapriya/starred{/owner}{/repo}", 
            "site_admin": false, 
            "login": "samapriya", 
            "type": "User", 
            "id": 6677629, 
            "followers_url": "https://api.github.com/users/samapriya/followers"
        }, 
        "url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/releases/8694239", 
        "created_at": "2017-11-29T02:48:25Z", 
        "target_commitish": "master", 
        "html_url": "https://github.com/samapriya/gee_asset_manager_addon/releases/tag/0.2.2", 
        "zipball_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/zipball/0.2.2", 
        "published_at": "2017-11-29T02:53:15Z", 
        "draft": false, 
        "prerelease": false, 
        "tarball_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/tarball/0.2.2", 
        "id": 8694239, 
        "name": "GEE Asset Manager with Addons"
    }, 
    "sender": {
        "following_url": "https://api.github.com/users/samapriya/following{/other_user}", 
        "gists_url": "https://api.github.com/users/samapriya/gists{/gist_id}", 
        "organizations_url": "https://api.github.com/users/samapriya/orgs", 
        "url": "https://api.github.com/users/samapriya", 
        "events_url": "https://api.github.com/users/samapriya/events{/privacy}", 
        "html_url": "https://github.com/samapriya", 
        "subscriptions_url": "https://api.github.com/users/samapriya/subscriptions", 
        "avatar_url": "https://avatars3.githubusercontent.com/u/6677629?v=4", 
        "repos_url": "https://api.github.com/users/samapriya/repos", 
        "received_events_url": "https://api.github.com/users/samapriya/received_events", 
        "gravatar_id": "", 
        "starred_url": "https://api.github.com/users/samapriya/starred{/owner}{/repo}", 
        "site_admin": false, 
        "login": "samapriya", 
        "type": "User", 
        "id": 6677629, 
        "followers_url": "https://api.github.com/users/samapriya/followers"
    }, 
    "repository": {
        "issues_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/issues{/number}", 
        "deployments_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/deployments", 
        "svn_url": "https://github.com/samapriya/gee_asset_manager_addon", 
        "has_wiki": true, 
        "forks_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/forks", 
        "mirror_url": null, 
        "stargazers_count": 6, 
        "subscription_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/subscription", 
        "notifications_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/notifications{?since,all,participating}", 
        "collaborators_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/collaborators{/collaborator}", 
        "updated_at": "2017-10-30T17:56:31Z", 
        "private": false, 
        "pulls_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/pulls{/number}", 
        "owner": {
            "following_url": "https://api.github.com/users/samapriya/following{/other_user}", 
            "gists_url": "https://api.github.com/users/samapriya/gists{/gist_id}", 
            "organizations_url": "https://api.github.com/users/samapriya/orgs", 
            "url": "https://api.github.com/users/samapriya", 
            "events_url": "https://api.github.com/users/samapriya/events{/privacy}", 
            "html_url": "https://github.com/samapriya", 
            "subscriptions_url": "https://api.github.com/users/samapriya/subscriptions", 
            "avatar_url": "https://avatars3.githubusercontent.com/u/6677629?v=4", 
            "repos_url": "https://api.github.com/users/samapriya/repos", 
            "received_events_url": "https://api.github.com/users/samapriya/received_events", 
            "gravatar_id": "", 
            "starred_url": "https://api.github.com/users/samapriya/starred{/owner}{/repo}", 
            "site_admin": false, 
            "login": "samapriya", 
            "type": "User", 
            "id": 6677629, 
            "followers_url": "https://api.github.com/users/samapriya/followers"
        }, 
        "full_name": "samapriya/gee_asset_manager_addon", 
        "issue_comment_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/issues/comments{/number}", 
        "contributors_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/contributors", 
        "id": 87708514, 
        "keys_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/keys{/key_id}", 
        "issue_events_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/issues/events{/number}", 
        "tags_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/tags", 
        "archived": false, 
        "downloads_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/downloads", 
        "assignees_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/assignees{/user}", 
        "contents_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/contents/{+path}", 
        "has_pages": false, 
        "git_refs_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/git/refs{/sha}", 
        "open_issues_count": 0, 
        "name": "gee_asset_manager_addon", 
        "has_projects": true, 
        "clone_url": "https://github.com/samapriya/gee_asset_manager_addon.git", 
        "watchers_count": 6, 
        "git_tags_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/git/tags{/sha}", 
        "labels_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/labels{/name}", 
        "forks": 3, 
        "size": 118, 
        "homepage": "", 
        "fork": false, 
        "milestones_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/milestones{/number}", 
        "commits_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/commits{/sha}", 
        "releases_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/releases{/id}", 
        "description": "Google Earth Engine Asset Manager with Useful Addons", 
        "archive_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/{archive_format}{/ref}", 
        "comments_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/comments{/number}", 
        "events_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/events", 
        "default_branch": "master", 
        "html_url": "https://github.com/samapriya/gee_asset_manager_addon", 
        "compare_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/compare/{base}...{head}", 
        "trees_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/git/trees{/sha}", 
        "watchers": 6, 
        "git_url": "git://github.com/samapriya/gee_asset_manager_addon.git", 
        "forks_count": 3, 
        "merges_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/merges", 
        "has_issues": true, 
        "ssh_url": "git@github.com:samapriya/gee_asset_manager_addon.git", 
        "blobs_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/git/blobs{/sha}", 
        "git_commits_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/git/commits{/sha}", 
        "hooks_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/hooks", 
        "has_downloads": true, 
        "languages_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/languages", 
        "license": {
            "spdx_id": "Apache-2.0", 
            "url": "https://api.github.com/licenses/apache-2.0", 
            "name": "Apache License 2.0", 
            "key": "apache-2.0"
        }, 
        "language": "Python", 
        "url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon", 
        "subscribers_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/subscribers", 
        "created_at": "2017-04-09T12:58:22Z", 
        "pushed_at": "2017-11-29T02:53:15Z", 
        "teams_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/teams", 
        "open_issues": 0, 
        "branches_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/branches{/branch}", 
        "statuses_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/statuses/{sha}", 
        "stargazers_url": "https://api.github.com/repos/samapriya/gee_asset_manager_addon/stargazers"
    }
}
```

**Comment by samapriya** [comment] 2017-11-29 12:47
Also fixed after deleting and re-releasing. Seems to be an intermittent issue but would be great to get to the root cause

**Comment by krzysztof** [comment] 2017-11-29 16:04
We have just deployed a fix, which should resolve this - sorry for the issues over the last few days. Closing for now, please reopen if this happens again.

**Closed by krzysztof** 2017-11-29 16:04 UTC

**Comment by ManavalanG** [comment] 2017-11-29 16:40
@krzysztof Is it necessary to delete and make a new release for this fix to work?

**Comment by krzysztof** [comment] 2017-11-29 17:14
@ManavalanG No, although all failed releases will not be automatically archived - you need to create make a new release (same or new version).
