### ISSUE TITLE
HTTP/500 when uploading > 50GB in single deposition

### ISSUE THREAD

**Issue by valhallasw** [zenodo/zenodo#693] opened 2016-08-08 12:04 UTC
During the upload of a large-ish dataset (80GB total), I received HTTP/500 errors. This seems to occur when the total size of the upload surpasses 50GB (49GB is OK, and when I remove a file to make more space, the next upload succeeds). [config.py](https://github.com/zenodo/zenodo/blob/a75cd964e372d12aba3b8a9ceebb073c012daa17/zenodo/modules/deposit/config.py#L43) suggests that there is indeed a 50GB quota.

Is this limit on purpose, or is it a limitation of the backend?

In any case, it would be good to
 * return a clear error message (instead of an http/500), both in the web interface and the REST API,
 * document this limitation in the FAQ

I'd be happy to provide a patch for both, but I can't find the actual uploading code. The uploading code should be defined as [invenio_deposit_rest.depid_files](https://github.com/inveniosoftware/invenio-deposit/blob/408687114eb434cc81e1e42b47e995ee9661b454/tests/test_views_rest.py#L226), but I can't find where that is defined...

**Comment by valhallasw** [comment] 2016-08-08 12:18
After a bit more searching in the repositories, I suppose this is the code that triggers the HTTP/500:
https://github.com/inveniosoftware/invenio-files-rest/blob/75bfbb59ebac5576123cbf827a187b21e39098a7/invenio_files_rest/views.py#L425

FileSizeErrors do not seem to be caught/handled anywhere, and exceptions normally trigger http/500's.

**Comment by lnielsen** [comment] 2016-08-08 13:19
We're in the process of a larger refactoring of the underlying repository platform Invenio and hope to soon launch. What you've found is not for the current production code. Also, the problem is not related to the code, but rather the underlying distributed file system we are currently using in production. We the new relaunch, we're moving to a different storage backend which doesn't have these issues.

**Closed by lnielsen** 2016-08-08 13:19 UTC

**Comment by lnielsen** [comment] 2016-08-08 13:24
FYI In the new system there's a 4GB limit for a single file. However, there's support for multipart upload similar to S3 (i.e. chunk the file client side and upload each piece - the server will put the pieces together again).
